name: shop
description: 'Tech Shop est une plateforme e-commerce spécialisée dans la vente de produits high-tech. Elle propose une large gamme d’articles : smartphones, ordinateurs, objets connectés, accessoires et équipements gaming. Facile d’utilisation, sécurisée et rapide, Tech Shop offre des produits de qualité issus des plus grandes marques, avec un service client réactif et des livraisons rapides.'

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.15.1
  animations: ^2.0.11
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  http: ^1.2.1
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/Illustration/
    - assets/flags/
    - assets/logo/
    - assets/screens/

  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900
